### PR TITLE
pkg: add 6 new ZTE apps

### PR DESCRIPTION
**Pull request by TubbyCat**
Added additional ZTE bloatware.
I have tested removal of the additions on a testing device manually with the unprivileged command "pm uninstall --user 0". 

For additional context and evidence: https://github.com/TubbyCat/droid_debloat_and_note/tree/main/experiments/zte

### CODE REVIEW

**Review by AnonymousWP — APPROVED** [review]

**Comment by TubbyCat** [comment]
uhh the pull needs maintainer approval. just heads up as it seems like something I would forget to do myself.

**Comment by AnonymousWP** [comment]
> uhh the pull needs maintainer approval. just heads up as it seems like something I would forget to do myself.

I am aware, but my approvals are merely meant as a second opinion, so that it's easier for the owner of this project to make a judgement in regards to commits/PRs.

**Comment by TubbyCat** [comment]
@AnonymousWP Since "Null" is not acceptable do I have to change the e.g. "dependencies null" to something else?

**Comment by AnonymousWP** [comment]
> @AnonymousWP Since "Null" is not acceptable do I have to change the e.g. "dependencies null" to something else?

That's not needed, but thanks. Null should work.

**Comment by 0x192** [comment]
Thanks for your contribution! (and sorry for my poor reactivity)

Can you upload the APK of `com.zte.burntest.camera` and `com.zte.contacts.sub` (here or on https://www.apkmirror.com/) ?

```
adb shell pm path <package> # return the path of the app
adb pull <path> # fetch the APK from the phone
```

One-liner if you are on MacOS or Linux :

```bash
adb pull $(adb shell pm path com.zte.burntest.camera | sed 's/package://g')
adb pull $(adb shell pm path com.zte.contacts.sub | sed 's/package://g')
```

PS: I had a big laugh! You work in healthcare right? xD
> Put another way, debloating a phone can be likened to a person with four appendices deciding to premptively get an appendectomy -- life is tough for a mutant. Their inflated chance of appendicitis is gone, but they can still die of a heart attack.
https://github.com/TubbyCat/droid_debloat_and_note

**Comment by 0x192** [comment]
@TubbyCat ? :slightly_smiling_face:

**Comment by 0x192** [comment]
@TubbyCat Feel free to ping me here if you come back

**Pull request merged**
