### PR TITLE
pkg: add 15 new Vivo/iQOO apps

### PR DESCRIPTION
**Pull request by Vinfall**
## Description

All these are tested on my phone and basic functions are not impaired. This PR should also solve #274.

## Added

- `com.bkk.theme`
- `com.bbk.iqoo.logsystem`
- `com.mobile.iroaming`
- `com.vivo.space`
- `com.baidu.input_vivo`
- `com.bbk.calendar`
- `com.vivo.share`
- `com.yozo.vivo.office`
- `com.vivo.browser`
- `com.vivo.dream.weather`
- `com.vivo.hybrid`
- `com.vivo.puresearch`
- `com.vivo.voicewakeup`
- `com.bbk.appstore`
- `com.bbk.account`

### CODE REVIEW

**Comment by Vinfall** [comment]
I close #279 as I don't know how to resolve the conflicts XD, so I simply create a new branch, pull the changes, and commits again to make a new PR.

**Comment by 0x192** [comment]
Thanks for you contribution and sorry for not being very reactive. Reviewing these kind of pull requests takes some time and I also have to spend time working on UAD itself (when I found the motivation on my free time :roll_eyes:)

I added some more documentation. Do you remember what Voice Wakup is? There is some kind of voice recognition involved but I'm note sure what exactly it does ? It just wake up the phone when you say a special word?

**Comment by Vinfall** [comment]
> Reviewing these kind of pull requests takes some time...

I understand full-heatedly! Maintaining such project is really time-consuming and especially so when everything is included in a single json file. Thank you for your dedication to this. And luckily I forgot to close the PR despite its inactivity XD.

> Do you remember what Voice Wakup is? There is some kind of voice recognition involved but I'm note sure what exactly it does ? It just wake up the phone when you say a special word?

From my test and the package activities description, Voice Wakeup is used to trigger the built-in voice assistant `Jovi` (just like `Bixby` on Samsung, Google Assistant or Siri) by certain keywords. It does have the ability to wake up the phone, but I'd call it kind of a *bonus* for triggering `Jovi`. I found this one does the same thing like `com.vivo.voicewakeup`.

https://github.com/0x192/universal-android-debloater/blob/9ec80c480fc8acd7b0890ec43d72afd91ec18779/resources/assets/uad_lists.json#L4439-L4447

The description can be changed from

```json
  {
    "id": "com.vivo.voicewakeup",
    "list": "Oem",
    "description": "Voice wake-up.",
    "dependencies": null,
    "neededBy": null,
    "labels": null,
    "removal": "Expert"
  },
```

to

```json
  {
    "id": "com.vivo.voicewakeup",
    "list": "Oem",
    "description": "Voice wake-up for using Jovi (voice assistant).",
    "dependencies": null,
    "neededBy": null,
    "labels": null,
    "removal": "Expert"
  },
```

I'm not sure how can I update the description myself. I just update `uad-lists.json` on my iQOO branch and push it, or merge your changes into the branch and solve the conflicts from here?

**Comment by 0x192** [comment]
Thanks for your reactivity! :D

All good! I updated the description and fixed the conflicts!

**Pull request merged**
