### PR TITLE
Add new Oppo bloatware

### PR DESCRIPTION
**Pull request by dianariyanto**
Adware found on Oppo a3s (CPH1803)

### CODE REVIEW

**Comment by 0x192** [comment]
Thanks for your contribution and sorry for the late reply. Could you provide me the `com.nearme.deamon` apk? 

```bash
adb shell pm path com.nearme.deamon # return the path of the app
adb pull <path> # fetch the APK from the phone
```

The current description doesn't seem right. The reddit thread refers to `"com.nearme.atlas` not `com.nearme.deamon`

**Comment by 0x192** [comment]
Thanks for the description update but could you still upload the APK please? :slightly_smiling_face:

**Comment by dianariyanto** [comment]
Sorry, I have given the Oppo A3s to my brother. So I can no longer provide info about bloatware on this device other than what I have included in this PR. But you can still merge this PR by editing or deleting part of the unverified list. Sorry I can't continue this contribution, but maybe next time I'll add to the list of bloatware I've found on other devices.

Thank you for building this great app.

**Comment by 0x192** [comment]
No problem! Thanks you for taking the time to create this pull request in the first place.

**Pull request merged**
