### PR TITLE
pkg: add 51 packages and an extra list "WearOS"

### PR DESCRIPTION
**Pull request by uwuclxdy**
I was debloating my Watch5 and I found out that it would be much faster if there were descriptions of watch-specific aps on UAD as well. It took me around two days of research and testing that would took me about half an hour if the descriptions I provided were there. Most of the packages I described are from my watch.

I hope they help someone if you decide to add WearOS as another category. 

There are some more undocumented app that I'm willing to provide description for, I just need a little bit of motivation.

### CODE REVIEW

**Review by uwuclxdy — COMMENTED** [review]
accidentally pressed commit changes

**Comment by TheSloPro** [comment]
72 packages in total now

`{
    "id": "com.google.android.wearable.assistant",
    "list": "WearOS",
    "description": "Google Assistant for Android wearables.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.google.android.wearable.batteryservices",
    "list": "WearOS",
    "description": "It's used to manage battery-related things on Android smartwatches, like monitoring the battery level, managing power consumption (auto battery saving I think), and handling battery-related events (pop-up when battery at 15%, etc.). It is typically used by developers to create battery-aware applications for wearable devices.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.advancedcallservice",
    "list": "Oem",
    "description": "Advanced Calling feature on an Android is a feature that allows you to make calls while using other applications with the use of CELLULAR DATA. In order for this feature to work, HD Voice must be enabled in settings.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.google.android.clockwork.oemsetup",
    "list": "WearOS",
    "description": "Installs carrier apps after the first time setup. Haven't noticed any concequences after uninstalling. I also saw some similar bloatware packages on the net, ending with clockwork.gestures.tutorial - first time use tutorial or clockwork.flashlight, clockwork.nfc, clockwork.brightness",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recommended"
  },
  {
    "id": "com.google.android.apps.wearable.retailattractloop",
    "list": "WearOS",
    "description": "Demo mode - you see it in the stores (the video playing while idle).",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recommended"
  },
  {
    "id": "com.samsung.android.mediacontroller",
    "list": "WearOS",
    "description": "Ability to controls phone's audio from your watch.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recommended"
  },
  {
    "id": "com.samsung.android.shealthmonitor",
    "list": "Oem",
    "description": "Samsung Health Monitor\n\nEnables you to record ECG and blood pressure.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recommended"
  },
  {
    "id": "com.samsung.android.watch.cameracontroller",
    "list": "WearOS",
    "description": "Mirrors phone's camera to your watch. I can't find a use case for my usage. Safe to remove.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recommended"
  },
  {
    "id": "com.samsung.android.watch.findmywatch",
    "list": "WearOS",
    "description": "The watch will start ringing, if connected to phone via BT or WiFi, when pressing 'start ringing' on the phone. Also fetches location and is able to lock or factory reset.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.findmyphone",
    "list": "WearOS",
    "description": "The phone will start ringing, if connected to watch via BT or WiFi, when pressing 'start ringing' on the watch.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.runestone.app",
    "list": "WearOS",
    "description": "Customization Service from Samsung. IMHO doesn't do anything useful.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recommended"
  },
  {
    "id": "com.samsung.android.watch.watchface.analoguefont",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.animal",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.aremoji",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.basicclock",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.basicdashboard",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.bespoke",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.bitmoji",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.boldindex",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.digitalfont",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.digitalmodular",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.dualwatch",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.dynamicfont",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.gradientfont",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.healthmodular",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.infomodular",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.large",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.livewallpaper",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.mypebble",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.myphoto",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.mystyle",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.premiumanalog",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.simpleanalogue",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.simplecomplication",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.superfiction",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.together",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.typography",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.weather",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.analogmodular",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.simpleclassic",
    "list": "WearOS",
    "description": "Preinstalled watchface.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.emergency",
    "list": "WearOS",
    "description": "Watchface in the emergency launcher.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.watchface.companionhelper",
    "list": "WearOS",
    "description": "Watchfaces fail to load without this. Removing it also breaks editing and changing watchfaces.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Expert"
  },
  {
    "id": "com.samsung.android.watch.watchface.tickingsound",
    "list": "WearOS",
    "description": "Ticking sound on watchfaces that support it.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.weather",
    "list": "WearOS",
    "description": "Weather application from Samsung.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recommended"
  },
  {
    "id": "com.samsung.android.watch.worldclock",
    "list": "WearOS",
    "description": "Worldclock app. This also includes a widget, displaying time in different time zones.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recommended"
  },
  {
    "id": "com.samsung.android.wear.blockednumber",
    "list": "WearOS",
    "description": "Blocked number storage. Doesn't affect the dialer or contacts.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.wear.musictransfer",
    "list": "WearOS",
    "description": "Used to sync music with watch.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.wearable.setupwizard",
    "list": "WearOS",
    "description": "Safe to remove after first time setup.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recommended"
  },
  {
    "id": "com.samsung.android.wear.contacts.sync",
    "list": "WearOS",
    "description": "Handles 'open on phone' events. Also, settings often crash when this uninstalled.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Expert"
  },
  {
    "id": "com.android.cts.ctsshim",
    "list": "WearOS",
    "description": "Basically an app for devs to compatibility test their app.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.cidmanager",
    "list": "Oem",
    "description": "In order to ensure that a user’s phone receives the appropriate firmware updates, this app is used to identify the carrier network. In other words - it helps to ensure that the correct country-specific firmware is delivered OTA.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Expert"
  },
  {
    "id": "com.samsung.packageinstalleroverlay",
    "list": "Oem",
    "description": "It's used to display an overlay window when installing or updating apps. Shows information about the app and provides the user with the option to cancel the process. Probably breaks manual installation of apps (needs more testing).",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Expert"
  },
  {
    "id": "com.samsung.android.wcs.exstention",
    "list": "WearOS",
    "description": "Samsung Internet Extensions\nSamsung Internet for Android allows users to customize their browsing experience by installing extensions, which are additional software packages that add new features and functionality to the browser and help developers offer tailored services to users on mobile devices.\n\nNOTE: Disabling this broke the UI on my Watch5 for some reason so PROCEED WITH CAUTION.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.stextclassifier",
    "list": "Oem",
    "description": "From https://developer.android.com/reference/android/view/textclassifier/TextClassifier:\nInterface for providing text classification related features.\n\nThe TextClassifier may be used to understand the meaning of text, as well as generating predicted next actions based on the text.\n\nSo it got something to do with text/spelling correction? But a samsung implementation of it. It needs some further testing, so far it doesn't affect even the autocorrect.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.sec.android.soagent",
    "list": "Oem",
    "description": "System application that is responsible for checking and installing software updates.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.packageinstalleroverlay",
    "list": "Oem",
    "description": "",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Expert"
  },
  {
    "id": "com.google.android.wearable.healthservices",
    "list": "WearOS",
    "description": "Health Services by Google\nPlay Store link: https://play.google.com/store/apps/details?id=com.google.android.wearable.healthservices&hl=en_US&gl=US\n\nDisabling this on my Watch5 broke heart rate measuring and some workouts.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Expert"
  },
  {
    "id": "com.samsung.android.service.health",
    "list": "WearOS",
    "description": "Health Platform\n\nIt is a data aggregator. You can use it to link multiple health apps (like Strava, google fit etc) together. This app will unify their collected data and store them all together.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Expert"
  },
  {
    "id": "com.samsung.android.wear.shealth",
    "list": "WearOS",
    "description": "Samsung Health app for WearOS.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.wearable.samsungaccount",
    "list": "WearOS",
    "description": "Samsung account settings. Breaks settings app if uninstalled.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Expert"
  },
  {
    "id": "com.samsung.android.watch.timer",
    "list": "WearOS",
    "description": "Timer",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recomended"
  },
  {
    "id": "com.samsung.android.watch.stopwatch",
    "list": "WearOS",
    "description": "Stopwatch",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recomended"
  },
  {
    "id": "com.samsung.android.watch.screencapture",
    "list": "WearOS",
    "description": "This is responsible for taking screenshots.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.flashlight",
    "list": "WearOS",
    "description": "Flashlight",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.samsung.android.watch.compass",
    "list": "WearOS",
    "description": "Samsung Compass app.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recomended"
  },
  {
    "id": "com.samsung.android.watch.alarm",
    "list": "WearOS",
    "description": "Alarms.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recomended"
  },
  {
    "id": "com.samsung.android.storage.watchstoragemanager",
    "list": "WearOS",
    "description": "Storage manager. Based on internet posts it's not safe to disable.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Expert"
  },
  {
    "id": "com.samsung.android.watch.timer",
    "list": "WearOS",
    "description": "Timer app from Samsung.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recomended"
  },
  {
    "id": "com.samsung.android.gallery.watch",
    "list": "WearOS",
    "description": "Gallery app",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
  {
    "id": "com.google.android.wearable.ambient",
    "list": "WearOS",
    "description": "It's like doze on Android phones. Not recommended to disable, as this package reduces battery drain when idle.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Expert"
  },
  {
    "id": "com.google.android.apps.wearable.settings",
    "list": "WearOS",
    "description": "Settings",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Expert"
  },
  {
    "id": "com.android.modulemetadata",
    "list": "aosp",
    "description": "It's used to manage and store metadata about installed modules, and is accessed by the system server. Breaks some core functionality if disabled.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Expert"
  }`

**Comment by uwuclxdy** [comment]
72 packages in total as of right now

**Comment by AnonymousWP** [comment]
This looks good, nice work! Because of many changes, I'm not going to review it this time, but I'll leave it to @0x192 as he's the maintainer of this project.

**Comment by uwuclxdy** [comment]
> This looks good, nice work! Because of many changes, I'm not going to review it this time, but I'll leave it to @0x192 as he's the maintainer of this project.

~Who are you? Noone asked you to do this, it has no benefit to just pointlessly comment on every single issue.~

> I'm sorry for this lol

**Comment by AnonymousWP** [comment]
> > This looks good, nice work! Because of many changes, I'm not going to review it this time, but I'll leave it to @0x192 as he's the maintainer of this project.
> 
> Who are you? Noone asked you to do this, it has no benefit to just pointlessly comment on every single issue.

What?? Why so offended? I'm just trying to help and contribute to this project to make it better. Who are you to prohibit me from commenting on people's issue and helping out?

The reason why I comment is because 0x192 sometimes takes long to reply, and to prevent people from feeling like their PR is useless, I take the time to reply. Also, I don't do this on every issue; I make PRs most of the time.

But hey, no problem for helping. You have a good day, too.

**Comment by uwuclxdy** [comment]
com.android.providers.blockednumber breaks Watch5 manager (i keep getting ANR popups and can't pair with my watch).

**Comment by uwuclxdy** [comment]
Anything happening yet?

**Comment by 0x192** [comment]
Thanks you @TheSloPro for the time you spent on this big contribution! I appreciate that you really tried to document all these apps.

No need to be aggressive towards @AnonymousWP though.

Sorry for the delay. Releasing `v0.6` was my main focus (it will be released tonight) and I set aside the pull requests.

**Comment by uwuclxdy** [comment]
I am sorry, but yeah nice to see development of this great app!

**Comment by 0x192** [comment]
Merged! :tada:

**Comment by 0x192** [comment]
Well... no `v0.6` tonight. I found an incoherent behavior when testing the backup/restore feature...

It's time for debugging and more comprehensive testing.

**Comment by AnonymousWP** [comment]
> Well... no `v0.6` tonight. I found an incoherent behavior when testing the backup/restore feature...
> 
> It's time for debugging and more comprehensive testing.

Ahh, too bad. Was looking forward to it. Hopefully it can be easily fixed.

**Pull request merged**
