### PR TITLE
feat: add an overview of all the selected packages

### PR DESCRIPTION
**Pull request by 0x192**
Last feature before `v0.6`. I initially only wanted to fix a bug and (finally) release `v0.6` this weekend but during my tests, I realized that the way UAD handles the multi-selection of packages across Android users and UAD filters (Recommendation, package State...) was very confusing.

It's not trivial to handle multi-users when packages state are different. What to do when all packages of all Android users are selected and that they don't have the same state? If you select an enabled package on `user 0` , you probably want to uninstall it for the others users (if you let the settings _affects all users..._ enabled). UAD will always enforce the wanted state for all the users based on the currently selected user. This pull request is an attempt to explain this in the simplest way possible to the user.

TODO: 
- [x] Update text for Disable mode
- [x] Improve UX. It's still very weird

<details>
<summary>Here is an insight of the feature</summary>

image

</details>

Better ideas or suggestion are welcomed.

### CODE REVIEW

**Comment by Dokujack52** [comment]
Wieso funktioniert das Teil nicht mal Ansatzweise ?
Ausser nen Riesenfenster und ne Mitteilung das das Tool das Handy sucht passiert nichts, ist das nen Scherztool ???

**Comment by 0x192** [comment]
I fixed some bugs and improved the UX by adding some colors and moved the example in a tooltip.

<details>
<summary>Final result</summary>

image

</details>

----
@Dokujack52 

Seriously? :unamused:

1) Do you really think your comment makes people want to help you?
2) You posted a completely off-topic comment here.
3) You didn't even try to write in English
4) You didn't bother to check [similar issues](https://github.com/0x192/universal-android-debloater/issues?q=is%3Aissue+label%3Ainvalid+is%3Aclosed)
5) You didn't provide any information detailing what you have tried

**Comment by Dokujack52** [comment]
Ich Schreibe Deutsch weil das meine Sprache ist ganz Einfach, wenn du damit nen Problem hast, Pech GEhabt. Wenn man was erreichen will mit seiner app sollte man Mehrsprachig eingestellt sein oder einen Deutschen Bereich dazu Fügen, da man hier Anscheinend dazu zu Faul ist Schreibe ich eben in Deutsch, dazu kommt das die Gesamt Hirachi des Forum - sofern man den Softwareschrott so nennen kann - ein Totaler Softwareschrott ist total unübersichtlich oist, also halt den Ball flach.

**Comment by AnonymousWP** [comment]
> Ich Schreibe Deutsch weil das meine Sprache ist ganz Einfach, wenn du damit nen Problem hast, Pech GEhabt. Wenn man was erreichen will mit seiner app sollte man Mehrsprachig eingestellt sein oder einen Deutschen Bereich dazu Fügen, da man hier Anscheinend dazu zu Faul ist Schreibe ich eben in Deutsch, dazu kommt das die Gesamt Hirachi des Forum - sofern man den Softwareschrott so nennen kann - ein Totaler Softwareschrott ist total unübersichtlich oist, also halt den Ball flach.

Just use a translator like DeepL man. Do you really expect the majority of the users to use a translator just because you don't speak/write in English? That's selfish. You're the minority, so you should be the one using a translator. After all, English is a world language; German isn't.

**Comment by Dokujack52** [comment]
Was für eine Witzfigur, ich lach mich gleich tot.

**Comment by AnonymousWP** [comment]
May I ask what the status of this PR is? When do you plan to merge this PR, as tasks have been marked as done. I'm looking forward to the new release! 😄

**Comment by 0x192** [comment]
> May I ask what the status of this PR is? When do you plan to merge this PR, as tasks have been marked as done. I'm looking forward to the new release! smile

It's finally done! I added the list of all selected packages in the recap.

<details>
<summary>Final result</summary>

image

</summary>

**Comment by AnonymousWP** [comment]
> 

Yay, thanks. Now what's left is a new release and merging PRs. 😁

**Pull request merged**
