### PR TITLE
refacotr: improve error handling

### PR DESCRIPTION
**Pull request by nozwock**
- Remove unwrap calls
- Don't change func signatures for func which don't already return Result/Option

Would appreciate feedback as I'm a beginner to Rust :+1:

### CODE REVIEW

**Comment by nozwock** [comment]
The app also panics on every exit due to this `unwrap_err` call here:
https://github.com/0x192/universal-android-debloater/blob/5ea61774cb6d1b19bc257f428cbea2745baa09ea/src/gui/mod.rs#L328
```
thread 'main' panicked at 'called `Result::unwrap_err()` on an `Ok` value: ()', src/gui/mod.rs:328:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by 0x192** [comment]
Yehee! You are officially my first Rust contributor! :tada: 

Thanks for your help! The current error handling system is something I'd like to overhaul since a long time. There too much `unwrap` indeed. 
 
The idea would be to use something like [`error-stack`](https://github.com/hashintel/hash/tree/main/packages/libs/error-stack) or [`eyre`](https://github.com/yaahc/eyre)  to have a much more simple, customizable and robust error handling system.

Until then, I'll still merge your pull request because you did a great job at removing many `unwrap` and propagating the error upward.  I remember very clearly when I used these `unwrap`. I was thinking "_Erf! This is bad. I need to use an error crate... but I don't have time right now..._". It's been several months ^^'

**Comment by 0x192** [comment]
I preferred to propagate the `Result` to `main()` to fix the panic on exit  :slightly_smiling_face:

**Comment by nozwock** [comment]
> Yehee! You are officially my first Rust contributor! :tada:

That's surprising, I had thought there would be a lot more already. :laughing:

> I preferred to propagate the `Result` to `main()` to fix the panic on exit :slightly_smiling_face:

Ya, I overlooked that one.

> - Remove unwrap calls
> - Don't change func signatures for func which don't already return Result/Option

I just had some issues when I tried to change some function signatures but the GUI code expected function signatures to be specific, and I couldn't really figure those one out since I don't know `iced`.

> The idea would be to use something like `error-stack` or `eyre` to have a much more simple, customizable and robust error handling system.

Yeah, I usually use `anyhow` for that, `eyre` and others looks interesting.

**Pull request merged**
