### PR TITLE
Update com.huawei.android.internal.app description

### PR DESCRIPTION
**Pull request by HT696**
I've tested it (Emui 8.0.0)

### CODE REVIEW

**Comment by KarlRamstedt** [comment]
What does "send files to apps" mean exactly?
Select files to upload to apps?

**Comment by HT696** [comment]
> What does "send files to apps" mean exactly? Select files to upload to apps?

"open with"(without the package it just opens, doesn't let you choose an app)
like editing using an image editor

also the share button which is used for uploading to messengers (without the package, it says no valid app found)
image
image
image

**Comment by KarlRamstedt** [comment]
> "open with"(without the package it just opens, doesn't let you choose an app)

Open with from what? You mean open with from within a file manager app?

**Comment by HT696** [comment]
> > "open with"(without the package it just opens, doesn't let you choose an app)
> 
> Open with from what? You mean open with from within a file manager app?

could be within a file manager or gallary or any other app that has access to certain files and the option "open with"
image


without this internal.app package anywhere where the menu(which is for choosing apps to proceeding further) pops up
it won't pop up anymore


and if there's not a default app, after tapping on the file it won't do anything 
(e.g in it won't pop the menu, shown in the attachment, and won't open the pdf file) 
image

further testing : certain apps(like the default downloads ui) replace it with their own menu but still won't do anything if you tap on a file that doesn't have a default application for openning
 "open with" option still works in them (but the "share" button,which is shown in the previous comment, still won't)

**Comment by KarlRamstedt** [comment]
Okay, so based on that, a fitting description would be this?

```json
    "description": "File sharing/opening API for Huawei devices?\nDisabling the package breaks the sharing menu globally, and the \"open with\" menu for Huawei apps.",
```

The easiest way to pull this into the main repo would probably be to delete your current fork ([HT696](https://github.com/HT696)/[universal-android-debloater](https://github.com/HT696/universal-android-debloater)), create a new one, and then copy-paste(make sure you also get the spaces before `"description"`) it into a new branch (you get an option for that in the web GUI).

Always try to use branches when doing pull requests; that makes it easier to manage merging.

**Comment by HT696** [comment]
thanks for the advice, in this case there wasn't an issue/incompatibility after merging the latest commit into my own fork but I can see how that comes in handy
I have a bunch of packages to add, I figured it would be better if I finish all of the changes I can contribute before pull req
> Okay, so based on that, a fitting description would be this?
> 
> ```json
>     "description": "File sharing/opening API for Huawei devices?\nDisabling the package breaks the sharing menu globally, and the \"open with\" menu for Huawei apps.",
> ```

not exactly, openwith menu may break in non-huawei apps too, "simple file manager" and "simple gallery" would be included but not "material files"
I guess it doesn't need every detail 
```json
"description": "File sharing API for Huawei devices?\nDisabling the package breaks the sharing(and openning with) menus globally, with a few excpetions."
```

**Comment by KarlRamstedt** [comment]
> openwith menu may break in non-huawei apps too

Aaaah, okay. So **_most_** apps then, with a few exceptions.
Also, uuuh, you got a spelling error there, and you missed the spacing at the start :P
There's a copy-pop-up when you hover your mouse over code blocks; just click it to copy the full block.

```json
    "description": "File sharing API for Huawei devices?\nDisabling the package breaks the sharing menu globally and the \"open with\" menu for most apps."
```

> in this case there wasn't an issue/incompatibility after merging the latest commit into my own fork but I can see how that comes in handy

Well, as long as the diff doesn't get f**ked :D
(which it doesn't seem like it is)

Best of luck with your changes!

**Pull request closed without merging**
