### PR TITLE
[Pkg] Update `com.miui.home` removal and description

### LINKED ISSUE #325: com.miui.home breaks menu button
My phone model: Mi 11 Lite 5G

**Packages documentation to update:**
```
com.miui.home
```
## Documentation change
Change It from Advanced to Expert

There was a lot of stuff to fill out here that i didn't know...
So let me just get it straight:
Deleting this package breaks the menu button (i only tested it on my phone sooo i don't know if other people have this issue)

### PR DESCRIPTION
**Pull request by AnonymousWP**
Fixes #325.

### CODE REVIEW

**Comment by 0x192** [comment]
Thanks! 

I really need to move forward on the `v0.6` milestone. I'll catch up with all the pull requests... soon. :no_mouth:

**Comment by AnonymousWP** [comment]
> Thanks!
> 
> I really need to move forward on the `v0.6` milestone. I'll catch up with all the pull requests... soon. 😶

Yeah because I noticed many PRs are still pending. Do you want to test all of them? You'd need specific devices to test all of them. imo it wouldn't take much time to merge PRs right?

**Comment by 0x192** [comment]
> Do you want to test all of them? You'd need specific devices to test all of them. imo it wouldn't take much time to merge PRs right?

I don't test them but I at least try to review them correctly and improve package description when needed. :slightly_smiling_face: 

I don't like adding new packages with too few documentation (e.g:  #350)

**Comment by AnonymousWP** [comment]
> > Do you want to test all of them? You'd need specific devices to test all of them. imo it wouldn't take much time to merge PRs right?
> 
> I don't test them but I at least try to review them correctly and improve package description when needed. :slightly_smiling_face: 
> 
> I don't like adding new packages with too few documentation (e.g:  #350)

Fair point, but in my opinion it's better to communicate that to the contributor (or creator of the issue) so that we can either improve that ourselves or ask the creator of the issue. Now, it'll just end up on the pile of PRs.

**Pull request merged**
