### PR TITLE
[Pkg] Unihertz Jelly 2

### PR DESCRIPTION
**Pull request by VeH-c**
Hope i'm during this right, see here for more details https://github.com/0x192/universal-android-debloater/commit/ccb5556365ac718c0458de20774bdb6b1c62e96b

### CODE REVIEW

**Comment by 0x192** [comment]
Sorry for the very late reply! Again, thanks for your investment!  :slightly_smiling_face: 

I don't know exactly why but I can't update this pull request. I've opened a new one: #439

**Comment by VeH-c** [comment]
image
Was not checked. Thought I did though.... I checked it now 

Any way, you didn't apply my fix'es to the URL's in the readme  https://github.com/0x192/universal-android-debloater/commit/ccb5556365ac718c0458de20774bdb6b1c62e96b

**Comment by 0x192** [comment]
> Any way, you didn't apply my fix'es to the URL's in the readme https://github.com/0x192/universal-android-debloater/commit/ccb5556365ac718c0458de20774bdb6b1c62e96b

This oversight had already been corrected :wink:

**Comment by VeH-c** [comment]
I disagree, A FAQ's link still points to gitlab 
image

**Comment by 0x192** [comment]
Oh! I'm dumb. I was looking at the second FAQ link in the README. I had completely forgotten there were 2.

Thanks for verifying! 

It is fixed: 368b963

**Pull request closed without merging**
