### PR TITLE
Huawei packages

### PR DESCRIPTION
**Pull request by marcingold22**
New packages from the last EMUI update.

### CODE REVIEW

**Comment by 0x192** [comment]
Thanks for your help!

Please add more details in the descriptions if you can.

**Comment by marcingold22** [comment]
Glad to help! I'll add them in the next days, together with more useless packages I found!

**Comment by marcingold22** [comment]
P.S. For now I'm using the old version (the one on GitLab) but some packages don't get removed (particularly the file manager) I don't know if there's any updated method on this version to remove it.

**Comment by marcingold22** [comment]
@0x192 Hi w1nst0n I added some descriptions!

**Pull request merged**
